version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  groups:
    crates-io:
      patterns:
        - "*"
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
