#!/usr/bin/env bash

set -ex

mkdir -p bogo
pushd bogo

git init --initial-branch main
git config core.sparsecheckout 1
cat << EOF > .git/info/sparse-checkout
go.mod
go.sum
ssl/test/runner
util/testresult
EOF

# fix on a tested point of rustls-testing branch
COMMIT=b81c2d26009b6cc5159b7a9cbdddfa4ae79defea
git fetch --depth=1 https://github.com/rustls/boringssl.git $COMMIT
git checkout $COMMIT
(cd ssl/test/runner && go test -c)

popd
