#!/bin/sh

# This script fetches, builds, and runs the BoringSSL
# TLS test tool ('BoGo') against rustls.

set -xe

cargo test --no-run --features dangerous_configuration

if [ ! -e bogo/ ] ; then
  ./fetch-and-build
fi

( cd bogo && ./bogo.test -shim-path ../../admin/covbin/bogo_shim \
     -shim-config ../config.json \
     -test.parallel 1 -num-workers 1 \
     -pipe -allow-unimplemented )
