#!/bin/sh

# This script fetches, builds, and runs the TryTLS
# TLS test tool against rustls.  The rustls-TryTLS test stub is
# by Joachim Viide -- https://github.com/HowNetWorks/trytls-rustls-stub

set -xe

if [ ! -e trytls/ ] ; then
  # NOTE: Upstream 'trytls' breaks on Python3.8. Once a fix PR[0] lands
  # we can remove this 'git+ssh' dependency in favour of upstream 'trytls'.
  #
  # [0]: https://github.com/ouspg/trytls/pull/314
  pip install \
    --prefix trytls/ \
    setuptools \
    git+ssh://git@github.com/cpu/trytls.git@cpu-python3.8-fix
fi

LIB_VERSIONS=(trytls/lib/*)
LIB_VERSION=$(basename "${LIB_VERSIONS[0]:-python-310}")

export PYTHONPATH=trytls/lib/"$LIB_VERSION"/site-packages/
./trytls/bin/trytls https "../target/${RELEASE:-debug}/examples/trytls_shim"
