[package]
name = "rustls-util"
version = "0.1.0-dev.1"
edition.workspace = true
license = "Apache-2.0 OR ISC OR MIT"
description = "Utilities for use with rustls"
repository = "https://github.com/rustls/rustls"

[features]
default = ["tracing"]
tracing = ["dep:tracing", "rustls/tracing"]

[dependencies]
rustls = { path = "../rustls", version = "0.24.0-dev.1", default-features = false }
tracing = { workspace = true, optional = true }

[lints]
workspace = true
