[package]
name = "rustls-post-quantum"
version = "0.3.0-dev.2"
edition.workspace = true
rust-version = "1.85"
license = "Apache-2.0 OR ISC OR MIT"
description = "Experimental support for post-quantum key exchange in rustls"
repository = "https://github.com/rustls/rustls"
categories = ["network-programming", "cryptography"]
autobenches = false

[dependencies]
rustls-aws-lc-rs = { version = "0.1.0-dev.1", path = "../rustls-aws-lc-rs" }
rustls = { version = "0.24.0-dev.1", path = "../rustls", default-features = false }

[lints]
workspace = true
