#!/bin/sh
#
# See https://users.rust-lang.org/t/tutorial-how-to-collect-test-coverages-for-rust-project/650

set -e

KCOV_KNOWN_GOOD=eedf728147b40a5887596d7b92f5ad94a17b3300

sudo apt-get install -y libcurl4-openssl-dev libelf-dev libdw-dev cmake gcc binutils-dev libiberty-dev

rm -rf kcov && mkdir -p kcov
cd kcov
wget https://github.com/SimonKagstrom/kcov/archive/$KCOV_KNOWN_GOOD.tar.gz
tar xzf $KCOV_KNOWN_GOOD.tar.gz
cd kcov-$KCOV_KNOWN_GOOD
mkdir build
cd build
cmake ..
make
sudo make install
