#!/bin/bash -e

get_crate_name()
{
  while [[ $# -gt 1 ]] ; do
    v=$1
    case $v in
      --crate-name)
        echo $2
        return
        ;;
    esac
    shift
  done
}

case $(get_crate_name "$@") in
  rustls|tlsclient|tlsserver|features|client_cert_verifier|server_cert_verifier|key_log_file_env|errors|api|badssl|bugs|topsites|bogo_shim|trytls_shim|bench)
    EXTRA=$COVERAGE_OPTIONS
    ;;
  *)
    ;;
esac

exec "$@" $EXTRA
