#!/bin/sh
set -xe

ADMIN=$(dirname "$0")
PREV=$(pwd)
if [ ! -d $ADMIN/rustfmt ] ; then
  git clone --depth 1 https://github.com/rust-lang/rustfmt $ADMIN/rustfmt
fi

if [ ! -x $ADMIN/rustfmt/target/release/cargo-fmt ] ; then
  cd $ADMIN/rustfmt
  export CFG_RELEASE=nightly
  export CFG_RELEASE_CHANNEL=nightly
  cargo build --release --features rustfmt,cargo-fmt
fi

cd $PREV
PATH=$ADMIN/rustfmt/release/:$PATH cargo-fmt
