#!/usr/bin/python

import sys

handshakes = []
bulks = []

def translate_resume(r):
    return {
        'no-resume': 'full',
        'sessionid': 'sessionid',
        'tickets': 'tickets'
    }[r]

for line in sys.stdin:
    line = line.strip()
    pieces = line.split()

    if pieces[0] == 'bulk':
        _, version, suite, direction, rate, unit = pieces
        bulks.append((suite, direction, float(rate), unit))
    elif pieces[0] == 'handshakes':
        _, version, suite, role, auth, resumed, rate, unit = pieces
        handshakes.append((suite, role, auth, resumed, float(rate), unit))

for suite, direction, rate, unit in sorted(bulks):
    print '`%s` | %s | %g %s' % (suite, direction, rate, unit)

for suite, role, auth, resumed, rate, unit in sorted(handshakes):
    print '`%s` <br> %s, %s, %s | %g %s' % (suite, role,
            auth if auth == 'server-auth' else 'mutual-auth',
            translate_resume(resumed), rate, unit)
