#!/usr/bin/env sh
# Extract the example usage into README.md

set -e

awk 'BEGIN { take=1 }/```tlsclient-mio/{take=0;print}take' < README.md > README.md.new
./target/debug/tlsclient-mio --help >> README.md.new
awk '/^```tlsclient-mio$/ {start=1;} start' < README.md > README.md.tmp
awk '/^```$/ {start=1;} start' < README.md.tmp >> README.md.new
mv README.md.new README.md

awk 'BEGIN { take=1 }/```tlsserver-mio/{take=0;print}take' < README.md > README.md.new
./target/debug/tlsserver-mio --help >> README.md.new
awk '/^```tlsserver-mio$/ {start=1;} start' < README.md > README.md.tmp
awk '/^```$/ {start=1;} start' < README.md.tmp >> README.md.new
mv README.md.new README.md
rm README.md.tmp
