use std::io;

use rustls::{Connection, VecInput};

mod key_log_file;
pub use key_log_file::KeyLogFile;

mod stream;
pub use crate::stream::{Stream, StreamOwned};

/// This function uses `io` to complete any outstanding IO for
/// the connection.
///
/// This is a convenience function which solely uses other parts
/// of the public API.
///
/// `output` holds TLS data waiting to be sent to the peer: records
/// generated by the connection (for example by [`process_new_packets()`])
/// are appended to it, and bytes written to `io` are drained from its front.
///
/// What this means depends on the connection state:
///
/// - If the connection [`is_handshaking()`], then IO is performed until
///   the handshake is complete.
/// - Otherwise, if `output` is not empty, it is written until it is
///   all written.
/// - Otherwise, if [`wants_read()`] is true, [`VecInput::read()`] is invoked
///   once.
///
/// The return value is the number of bytes read from and written
/// to `io`, respectively. Once both `read()` and `write()` yield `WouldBlock`,
/// this function will propagate the error.
///
/// Errors from TLS record handling (i.e., from [`process_new_packets()`])
/// are wrapped in an `io::ErrorKind::InvalidData`-kind error.
///
/// [`is_handshaking()`]: rustls::CommonState::is_handshaking
/// [`wants_read()`]: rustls::Connection::wants_read
/// [`process_new_packets()`]: rustls::Connection::process_new_packets
pub fn complete_io(
    io: &mut (impl io::Read + io::Write),
    input: &mut VecInput,
    received_plaintext: &mut Vec<u8>,
    output: &mut Vec<u8>,
    conn: &mut impl Connection,
) -> Result<(usize, usize), io::Error> {
    let mut eof = false;
    let mut wrlen = 0;
    let mut rdlen = 0;
    loop {
        let (mut blocked_write, mut blocked_read) = (None, None);
        let until_handshaked = conn.is_handshaking();

        if output.is_empty() && !conn.wants_read() {
            // We will make no further progress.
            return Ok((rdlen, wrlen));
        }

        let mut sent = 0;
        while sent < output.len() {
            match io.write(&output[sent..]) {
                Ok(0) => {
                    output.drain(..sent);
                    io.flush()?;
                    return Ok((rdlen, wrlen)); // EOF.
                }
                Ok(n) if n > output.len() - sent => {
                    // This is really unrecoverable, since the amount of data written
                    // is now unknown.  Consume all the potentially-written data in
                    // case the caller ignores the error.
                    // See <https://github.com/rustls/rustls/issues/2316> for background.
                    let available = output.len() - sent;
                    output.clear();
                    return Err(io::Error::other(format!(
                        "illegal write() return value ({n} > {available})"
                    )));
                }
                Ok(n) => {
                    wrlen += n;
                    sent += n;
                }
                Err(err) if err.kind() == io::ErrorKind::WouldBlock => {
                    blocked_write = Some(err);
                    break;
                }
                Err(err) => {
                    output.drain(..sent);
                    return Err(err);
                }
            }
        }
        output.drain(..sent);
        if wrlen > 0 {
            io.flush()?;
        }

        if !until_handshaked && wrlen > 0 {
            return Ok((rdlen, wrlen));
        }

        // If we want to write, but are WouldBlocked by the underlying IO, *and*
        // have no desire to read; that is everything.
        if let (Some(_), false) = (&blocked_write, conn.wants_read()) {
            return match wrlen {
                0 => Err(blocked_write.unwrap()),
                _ => Ok((rdlen, wrlen)),
            };
        }

        while !eof && conn.wants_read() {
            let read_size = match input.read(io) {
                Ok(0) => {
                    eof = true;
                    Some(0)
                }
                Ok(n) => {
                    rdlen += n;
                    Some(n)
                }
                Err(err) if err.kind() == io::ErrorKind::WouldBlock => {
                    blocked_read = Some(err);
                    break;
                }
                Err(err) if err.kind() == io::ErrorKind::Interrupted => None, // nothing to do
                Err(err) => return Err(err),
            };
            if read_size.is_some() {
                break;
            }
        }

        let error = conn
            .process_new_packets(input, output)
            .handle_all(received_plaintext)
            .err();

        if let Some(e) = error {
            // In case we have an alert to send describing this error, try a last-gasp
            // write -- but don't predate the primary error.
            let _ignored = write_and_drain(io, output);
            let _ignored = io.flush();
            return Err(io::Error::new(io::ErrorKind::InvalidData, e));
        };

        // If we want to read, but are WouldBlocked by the underlying IO, *and*
        // have no desire to write; that is everything.
        if output.is_empty()
            && let Some(error) = blocked_read
        {
            return match rdlen {
                0 => Err(error),
                _ => Ok((rdlen, wrlen)),
            };
        }

        // if we're doing IO until handshaked, and we believe we've finished handshaking,
        // but process_new_packets() has queued TLS data to send, loop around again to write
        // the queued messages.
        if until_handshaked && !conn.is_handshaking() && !output.is_empty() {
            continue;
        }

        let blocked = blocked_write.zip(blocked_read);
        match (eof, until_handshaked, conn.is_handshaking(), blocked) {
            (_, true, false, _) => return Ok((rdlen, wrlen)),
            (_, _, _, Some((e, _))) if rdlen == 0 && wrlen == 0 => return Err(e),
            (_, _, _, Some(_)) => return Ok((rdlen, wrlen)),
            (_, false, _, _) => return Ok((rdlen, wrlen)),
            (true, true, true, _) => return Err(io::Error::from(io::ErrorKind::UnexpectedEof)),
            _ => {}
        }
    }
}

/// Write the front of `output` to `io`, draining the bytes that were written.
fn write_and_drain(io: &mut dyn io::Write, output: &mut Vec<u8>) -> io::Result<usize> {
    let n = io.write(output)?;
    if n > output.len() {
        // This is really unrecoverable, since the amount of data written
        // is now unknown.  Consume all the potentially-written data in
        // case the caller ignores the error.
        // See <https://github.com/rustls/rustls/issues/2316> for background.
        let available = output.len();
        output.clear();
        return Err(io::Error::other(format!(
            "illegal write() return value ({n} > {available})"
        )));
    }
    output.drain(..n);
    Ok(n)
}
